with open('main.py', 'a', encoding='utf-8') as f:
    f.write("\n@app.get('/api/debug/area')\n")
    f.write("def api_debug_area():\n")
    f.write("    conn_v = get_conn('vulcano')\n")
    f.write("    try:\n")
    f.write("        cur = conn_v.cursor()\n")
    f.write("        cur.execute('''SELECT \n")
    f.write("            (SELECT SUM(U.METRAGEM) FROM UNIDADE U JOIN BLOCO B ON B.ID = U.IDBLOCO WHERE B.IDEMPREENDIMENTO = 5) as TOTAL_AREA,\n")
    f.write("            (SELECT SUM(U.METRAGEM) FROM VENDAUNIDADE VU JOIN VENDA V ON V.ID = VU.IDVENDA JOIN UNIDADE U ON U.ID = VU.IDUNIDADE JOIN BLOCO B ON B.ID = U.IDBLOCO WHERE B.IDEMPREENDIMENTO = 5 AND COALESCE(V.DISTRATO, 'N') NOT IN ('T', 'S', '1')) as SOLD_AREA\n")
    f.write("        FROM RDB$DATABASE''')\n")
    f.write("        res = cur.fetchone()\n")
    f.write("        return {'status': 'ok', 'res': str(res)}\n")
    f.write("    except Exception as e:\n")
    f.write("        return {'status': 'error', 'error': str(e)}\n")
    f.write("    finally:\n")
    f.write("        conn_v.close()\n")
