"""Banco OPERACIONAL do app (baixas, projetadas, usuários, parsers, importer...).

Historicamente um SQLite local (poc_database.sqlite). Com `APP_DB_KIND=postgres`
no .env, passa a usar um database Postgres (default `vulcano2`, mesmo servidor do
Questor) — permitindo que instância local e deploy compartilhem o mesmo estado.

`connect_app()` devolve uma conexão com contrato sqlite3-compatível:
  - placeholders `?` traduzidos para `%s` (fora de literais);
  - `conn.execute(...)` (atalho do sqlite3) suportado;
  - `cursor.lastrowid` emulado via lastval();
  - `conn.row_factory = sqlite3.Row` aceito (linhas acessáveis por índice e nome);
  - DDL inline traduzido (AUTOINCREMENT/DATETIME/datetime('now'));
  - reconexão automática em queda de conexão (consumidores de vida longa,
    ex. queue_watcher).

Ficam FORA deste adapter (arquivos SQLite próprios, não migram):
core/janitor (janitor_metrics.sqlite) e o checkpoint do langgraph
(agente_checkpoints.sqlite).
"""
from __future__ import annotations

import os
import re
import sqlite3

_BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))


def app_db_kind() -> str:
    return (os.environ.get("APP_DB_KIND") or "sqlite").strip().lower()


def sqlite_path() -> str:
    # Mesma resolução do main.py: env > backend/poc_database.sqlite > cwd (legado).
    if os.environ.get("POC_DATABASE_FILE"):
        return os.environ["POC_DATABASE_FILE"]
    p_backend = os.path.join(_BACKEND_DIR, "poc_database.sqlite")
    p_cwd = os.path.join(os.getcwd(), "poc_database.sqlite")
    if os.path.isfile(p_backend):
        return p_backend
    if os.path.isfile(p_cwd):
        return p_cwd
    return p_backend


def _pg_conninfo() -> dict:
    return {
        "host": os.environ.get("APP_PG_HOST") or os.environ.get("QUESTOR_PG_HOST", "127.0.0.1"),
        "port": int(os.environ.get("APP_PG_PORT") or os.environ.get("QUESTOR_PG_PORT", "5432")),
        "dbname": os.environ.get("APP_PG_DB", "vulcano2"),
        "user": os.environ.get("APP_PG_USER") or os.environ.get("QUESTOR_PG_USER", "postgres"),
        "password": os.environ.get("APP_PG_PASS") or os.environ.get("QUESTOR_PG_PASS", ""),
        "connect_timeout": int(os.environ.get("APP_PG_TIMEOUT", "10")),
    }


# ── Tradução SQLite → Postgres ────────────────────────────────────────────────
_DDL_AUTOINC_RE = re.compile(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE)
_DDL_DATETIME_RE = re.compile(r"\bDATETIME\b", re.IGNORECASE)
_DT_NOW_TEXT_RE = re.compile(r"\(\s*datetime\s*\(\s*'now'\s*\)\s*\)", re.IGNORECASE)


def _qmark_to_pyformat(sql: str) -> str:
    """`?` → `%s` apenas fora de literais 'single-quoted'; dobra `%` literais."""
    out, i, n, in_str = [], 0, len(sql), False
    while i < n:
        ch = sql[i]
        if in_str:
            out.append("%%" if ch == "%" else ch)
            if ch == "'":
                if i + 1 < n and sql[i + 1] == "'":  # '' escapado
                    out.append("'")
                    i += 1
                else:
                    in_str = False
        else:
            if ch == "'":
                in_str = True
                out.append(ch)
            elif ch == "?":
                out.append("%s")
            elif ch == "%":
                out.append("%%")
            else:
                out.append(ch)
        i += 1
    return "".join(out)


def translate_app(sql: str) -> str:
    sql = _DDL_AUTOINC_RE.sub("INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    sql = _DDL_DATETIME_RE.sub("TIMESTAMPTZ", sql)
    sql = _DT_NOW_TEXT_RE.sub("(now()::text)", sql)
    if "?" in sql or "%" in sql:
        sql = _qmark_to_pyformat(sql)
    return sql


# ── Linha híbrida (índice + nome), compatível com o uso de sqlite3.Row ────────
class _HybridRow(tuple):
    __slots__ = ()
    _fields: tuple = ()

    def __getitem__(self, key):
        if isinstance(key, str):
            return tuple.__getitem__(self, self._fields.index(key))
        return tuple.__getitem__(self, key)

    def keys(self):
        return list(self._fields)


def _hybrid_row_factory(cursor):
    fields = tuple(d.name for d in cursor.description) if cursor.description else ()
    cls = type("Row", (_HybridRow,), {"_fields": fields, "__slots__": ()})

    def make(values):
        return cls(values)
    return make


# ── Wrappers Postgres com contrato sqlite3 ────────────────────────────────────
class _AppPgCursor:
    def __init__(self, conn_wrapper, cur):
        self._cw = conn_wrapper
        self._cur = cur

    def execute(self, sql, params=None):
        self._cur = self._cw._exec(self._cur, sql, params, many=False)
        return self

    def executemany(self, sql, seq):
        self._cur = self._cw._exec(self._cur, sql, seq, many=True)
        return self

    @property
    def lastrowid(self):
        try:
            with self._cw._raw.cursor() as c2:
                c2.execute("SELECT lastval()")
                return c2.fetchone()[0]
        except Exception:
            return None

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def fetchmany(self, size=None):
        return self._cur.fetchmany(size) if size else self._cur.fetchmany()

    @property
    def description(self):
        return self._cur.description

    @property
    def rowcount(self):
        return self._cur.rowcount

    def close(self):
        try:
            self._cur.close()
        except Exception:
            pass

    def __iter__(self):
        return iter(self._cur)


class _AppPgConnection:
    """Conexão PG com contrato sqlite3: execute() na conexão, row_factory,
    commit/rollback/close e reconexão transparente em queda."""

    kind = "postgres"

    def __init__(self):
        self._raw = None
        self._row_factory = None
        self._connect()

    def _connect(self):
        import psycopg
        self._raw = psycopg.connect(**_pg_conninfo())

    # row_factory: aceitar sqlite3.Row (ou qualquer valor truthy) → linhas híbridas
    @property
    def row_factory(self):
        return self._row_factory

    @row_factory.setter
    def row_factory(self, value):
        self._row_factory = value

    def _mk_cursor(self):
        if self._row_factory is not None:
            return self._raw.cursor(row_factory=_hybrid_row_factory)
        return self._raw.cursor()

    def _exec(self, cur, sql, params, many):
        import psycopg
        tsql = translate_app(sql)
        try:
            if cur is None or cur.closed:
                cur = self._mk_cursor()
            if many:
                cur.executemany(tsql, list(params or []))
            else:
                cur.execute(tsql, params or None)
            return cur
        except psycopg.OperationalError:
            # conexão caiu (idle timeout/restart): reconecta e tenta 1x
            try:
                self._raw.close()
            except Exception:
                pass
            self._connect()
            cur = self._mk_cursor()
            if many:
                cur.executemany(tsql, list(params or []))
            else:
                cur.execute(tsql, params or None)
            return cur

    def cursor(self):
        return _AppPgCursor(self, self._mk_cursor())

    def execute(self, sql, params=None):
        c = _AppPgCursor(self, None)
        return c.execute(sql, params)

    def executemany(self, sql, seq):
        c = _AppPgCursor(self, None)
        return c.executemany(sql, seq)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        try:
            self._raw.rollback()
        except Exception:
            pass

    def close(self):
        try:
            self._raw.close()
        except Exception:
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, *exc):
        if exc_type:
            self.rollback()
        else:
            try:
                self.commit()
            except Exception:
                pass
        self.close()


def connect_app():
    """Conexão com o banco operacional do app (SQLite ou Postgres, por env)."""
    if app_db_kind() == "postgres":
        return _AppPgConnection()
    return sqlite3.connect(sqlite_path())
